// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhSHeMyNeG2V3cGUYnxaClU_yiCdUfSI',
    appId: '1:445198108948:web:5152afc35f5c8775e05a01',
    messagingSenderId: '445198108948',
    projectId: 'learn-49d6c',
    authDomain: 'learn-49d6c.firebaseapp.com',
    storageBucket: 'learn-49d6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyix2IBlrbuCB2DjoKv5yayCyN2efSsQ',
    appId: '1:445198108948:android:bc7b162d5cd069d3e05a01',
    messagingSenderId: '445198108948',
    projectId: 'learn-49d6c',
    storageBucket: 'learn-49d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PCG84APIEiNk-SkVYB83ebRvNyQhSv4',
    appId: '1:445198108948:ios:47cd6b69a104b3e2e05a01',
    messagingSenderId: '445198108948',
    projectId: 'learn-49d6c',
    storageBucket: 'learn-49d6c.appspot.com',
    iosBundleId: 'com.mchumasoftwares.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9PCG84APIEiNk-SkVYB83ebRvNyQhSv4',
    appId: '1:445198108948:ios:47cd6b69a104b3e2e05a01',
    messagingSenderId: '445198108948',
    projectId: 'learn-49d6c',
    storageBucket: 'learn-49d6c.appspot.com',
    iosBundleId: 'com.mchumasoftwares.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhSHeMyNeG2V3cGUYnxaClU_yiCdUfSI',
    appId: '1:445198108948:web:27c71a531cce292fe05a01',
    messagingSenderId: '445198108948',
    projectId: 'learn-49d6c',
    authDomain: 'learn-49d6c.firebaseapp.com',
    storageBucket: 'learn-49d6c.appspot.com',
  );
}